Add playwright

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,7 +1,7 @@
 version: 2.1
 
 jobs:
-  test:
+  rspec:
     docker:
       - image: cimg/ruby:3.2.2-node
     environment:
@@ -52,8 +52,64 @@ jobs:
       - store_artifacts:
           path: backend/log
 
+  playwright:
+    docker:
+      - image: cimg/ruby:3.2.2-node
+    environment:
+      DOCKER_BUILDKIT: 0
+    steps:
+      - checkout
+
+      - setup_remote_docker
+
+      - run:
+          name: Install Docker Compose
+          command: |
+            DOCKER_COMPOSE_VERSION=2.20.2
+            sudo curl -L "https://github.com/docker/compose/releases/download/v${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+            sudo chmod +x /usr/local/bin/docker-compose
+            docker-compose version
+
+      - run:
+          name: Verify POSTGRES_PASSWORD
+          command: |
+            if [ -z "${POSTGRES_PASSWORD}" ]; then
+              echo "Error: POSTGRES_PASSWORD is not set."
+              exit 1
+            else
+              echo "POSTGRES_PASSWORD is set."
+            fi
+
+      - run:
+          name: Create .env File
+          command: |
+            echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" > backend/.env
+            echo "RAILS_ENV=test" >> backend/.env
+
+      - run:
+          name: Build Backend Image
+          command: |
+            docker build --no-cache -t backend_image -f backend/Dockerfile.backend backend
+
+      - run:
+          name: Build Other Docker Images
+          command: |
+            docker-compose build
+
+      - run:
+          name: Run Playwright Tests
+          command: |
+            docker-compose run --rm playwright
+          when: always
+
+      - store_test_results:
+          path: backend/tmp/rspec_results
+
+      - store_artifacts:
+          path: backend/log
+
 workflows:
   version: 2
   test:
     jobs:
-      - test
+      - rspec
